### ISSUE TITLE
ubuntu 18.04 make error

### ISSUE THREAD

**Issue by gelinhe** [EmbersArc/Epigraph#5]
/usr/include/eigen3/Eigen/src/SparseCore/SparseMatrix.h: In instantiation of ‘Eigen::SparseMatrix<_Scalar, _Flags, _StorageIndex>::Scalar& Eigen::SparseMatrix<_Scalar, _Flags, _StorageIndex>::insertBackUncompressed(Eigen::Index, Eigen::Index) [with _Scalar = cvx::internal::Parameter; int _Options = 1; _StorageIndex = int; Eigen::SparseMatrix<_Scalar, _Flags, _StorageIndex>::Scalar = cvx::internal::Parameter; Eigen::Index = long int]’:
/usr/include/eigen3/Eigen/src/SparseCore/SparseMatrix.h:941:57:   required from ‘void Eigen::internal::set_from_triplets(const InputIterator&, const InputIterator&, SparseMatrixType&, DupFunctor) [with InputIterator = __gnu_cxx::__normal_iterator<Eigen::Triplet<cvx::internal::Parameter>*, std::vector<Eigen::Triplet<cvx::internal::Parameter> > >; SparseMatrixType = Eigen::SparseMatrix<cvx::internal::Parameter>; DupFunctor = Eigen::internal::scalar_sum_op<cvx::internal::Parameter, cvx::internal::Parameter>]’
/usr/include/eigen3/Eigen/src/SparseCore/SparseMatrix.h:995:92:   required from ‘void Eigen::SparseMatrix<_Scalar, _Flags, _StorageIndex>::setFromTriplets(const InputIterators&, const InputIterators&) [with InputIterators = __gnu_cxx::__normal_iterator<Eigen::Triplet<cvx::internal::Parameter>*, std::vector<Eigen::Triplet<cvx::internal::Parameter> > >; _Scalar = cvx::internal::Parameter; int _Options = 0; _StorageIndex = int]’
/home/gelinhe/test_ep/Epigraph/src/wrappers/socpWrapperBase.cpp:145:66:   required from here
/usr/include/eigen3/Eigen/src/SparseCore/SparseMatrix.h:896:31: error: no match for ‘operator=’ (operand types are ‘Eigen::internal::CompressedStorage<cvx::internal::Parameter, int>::Scalar {aka cvx::internal::Parameter}’ and ‘int’)
       return (m_data.value(p) = 0);
              ~~~~~~~~~~~~~~~~~^~~~
In file included from /home/gelinhe/test_ep/Epigraph/include/expressions.hpp:8:0,
                 from /home/gelinhe/test_ep/Epigraph/include/constraint.hpp:8,
                 from /home/gelinhe/test_ep/Epigraph/include/problem.hpp:8,
                 from /home/gelinhe/test_ep/Epigraph/include/wrappers/wrapperBase.hpp:3,
                 from /home/gelinhe/test_ep/Epigraph/include/wrappers/socpWrapperBase.hpp:3,
                 from /home/gelinhe/test_ep/Epigraph/src/wrappers/socpWrapperBase.cpp:1:
/home/gelinhe/test_ep/Epigraph/include/parameter.hpp:76:15: note: candidate: cvx::internal::Parameter& cvx::internal::Parameter::operator=(const cvx::internal::Parameter&)
         class Parameter
               ^~~~~~~~~
/home/gelinhe/test_ep/Epigraph/include/parameter.hpp:76:15: note:   no known conversion for argument 1 from ‘int’ to const cvx::internal::Parameter&’
/home/gelinhe/test_ep/Epigraph/include/parameter.hpp:76:15: note: candidate: cvx::internal::Parameter& cvx::internal::Parameter::operator=(cvx::internal::Parameter&&)
/home/gelinhe/test_ep/Epigraph/include/parameter.hpp:76:15: note:   no known conversion for argument 1 from ‘int’ to cvx::internal::Parameter&&’
Epigraph/CMakeFiles/epigraph.dir/build.make:206: recipe for target 'Epigraph/CMakeFiles/epigraph.dir/src/wrappers/socpWrapperBase.cpp.o' failed
make[2]: *** [Epigraph/CMakeFiles/epigraph.dir/src/wrappers/socpWrapperBase.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'Epigraph/CMakeFiles/epigraph.dir/all' failed
make[1]: *** [Epigraph/CMakeFiles/epigraph.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by EmbersArc** [comment]
What version of Eigen are you using? You will need 3.3.7 or higher. Unfortunately Ubuntu 18 ships with 3.3.4. I could fix this issue by either making some constructors implicit (I'd prefer not to) or by automatically downloading the appropriate Eigen version if only an old version could be found. I'll probably have to go with the first version since there are a lot of people using Ubuntu 18.04.

Let me know if using the latest Eigen fixes the issue for you.

**Comment by gelinhe** [comment]
Your project is really wonderful. I am ready to modify the project according to your tips. If the problem can be solved, I will inform you as soon as possible

**Comment by gelinhe** [comment]
> What version of Eigen are you using? You will need 3.3.7 or higher. Unfortunately Ubuntu 18 ships with 3.3.4. I could fix this issue by either making some constructors implicit (I'd prefer not to) or by automatically downloading the appropriate Eigen version if only an old version could be found. I'll probably have to go with the first version since there are a lot of people using Ubuntu 18.04.
> 
> Let me know if using the latest Eigen fixes the issue for you.

Your project is really wonderful. I am ready to modify the project according to your tips. If the problem can be solved, I will inform you as soon as possible

**Comment by gelinhe** [comment]
> What version of Eigen are you using? You will need 3.3.7 or higher. Unfortunately Ubuntu 18 ships with 3.3.4. I could fix this issue by either making some constructors implicit (I'd prefer not to) or by automatically downloading the appropriate Eigen version if only an old version could be found. I'll probably have to go with the latter option since there are a lot of people using Ubuntu 18.04.
> 
> Let me know if using the latest Eigen fixes the issue for you.

According to your tips, I have successfully solved the compilation problem in two ways:

（1）explicit Parameter(int const_ Value)  remove explicit.

(2) Put eigen3.3.7 directly on the source tree, and add include to cmakelist: include_directories(${CMAKE_ CURRENT_ SOURCE_ DIR}/eigen-3.3)

Remove

find_ package(Eigen3 REQUIRED NO_ MODULE)

target_ link_ libraries(epigraph Eigen3::Eigen)

Also successfully compiled.

The default eigen version of Ubuntu 18.04 is retained because many software depends on it

**Comment by gelinhe** [comment]
> What version of Eigen are you using? You will need 3.3.7 or higher. Unfortunately Ubuntu 18 ships with 3.3.4. I could fix this issue by either making some constructors implicit (I'd prefer not to) or by automatically downloading the appropriate Eigen version if only an old version could be found. I'll probably have to go with the latter option since there are a lot of people using Ubuntu 18.04.
> 
> Let me know if using the latest Eigen fixes the issue for you.

According to your tips, I have successfully solved the compilation problem in two ways:

（1）explicit Parameter(int const_ Value) it is possible to remove explicit.

(2) Put eigen3.3.7 directly on the source tree, and add include to cmakelist_ directories(${CMAKE_ CURRENT_ SOURCE_ DIR}/eigen-3.3)

Remove

find_ package(Eigen3 REQUIRED NO_ MODULE)

target_ link_ libraries(epigraph Eigen3::Eigen)

Also successfully compiled.

The default eigen version of Ubuntu 18.04 is retained because many software depends on it

**Comment by EmbersArc** [comment]
Thanks for the explanation of what worked for you. I found a different way to fix the issue. It should now work with at least Eigen version 3.3.0 and above (Ubuntu 16.04). Let me know if it works without any changes now.
