### ISSUE TITLE
The time for adding constrain is much longer than solving the qp problem in the test_mpc_qp.cpp.

### ISSUE THREAD

**Issue by szt008** [EmbersArc/Epigraph#7]
using namespace cvx;

#include <ctime>
    

TEST_CASE("MPC QP")
{
    // This test solves an MPC problem with quadratic programming.
    
    size_t T = 700; // time horizon

    Eigen::MatrixXd A(2, 2);
    A << 2, -1, 1, 0.2;
    Eigen::MatrixXd B(2, 1);
    B << 1, 0;
    Eigen::VectorXd x0(2);
    x0 << 3, 1;

    OptimizationProblem qp;

    // Create variables
    MatrixX x = qp.addVariable("x", 2, T + 1);
    MatrixX u = qp.addVariable("u", 1, T);

    // Dynamics
    for (size_t t = 0; t < T; t++)
    {
        qp.addConstraint(equalTo(x.col(t + 1), par(A) * x.col(t) + par(B) * u.col(t)));
    }

    // State and control limits
    qp.addConstraint(box(-5., x, 5.));

    // Equivalent to
    // qp.addConstraint(box(-2., u, 2.));
    qp.addConstraint(greaterThan(u, -2.));
    qp.addConstraint(lessThan(u, 2.));

    // Boundary constraints
    qp.addConstraint(equalTo(x.col(0), par(x0)));
    qp.addConstraint(equalTo(x.col(T), 0.));

    // Cost function
    qp.addCostTerm(x.squaredNorm() + u.squaredNorm());

    // Print the problem for inspection

    // Create and initialize the solver instance.
    osqp::OSQPSolver solver(qp);

    solver.setAlpha(1.);
    clock_t start,finish;
    start = clock();
    // Solve the problem and get the solution
    solver.solve(false);
    finish = clock();
    std::cout<<"runtime is "<<((double)(finish-start))/CLOCKS_PER_SEC<<std::endl;
    Eigen::MatrixXd x_sol = eval(x);
    Eigen::MatrixXd u_sol = eval(u);

    // Check solution
    for (size_t t = 0; t < T; t++)
    {
        const Eigen::VectorXd x_solution = x_sol.col(t + 1);
        const Eigen::VectorXd x_propagate = A * x_sol.col(t) + B * u_sol.col(t);
        const double max_error = (x_propagate - x_solution).cwiseAbs().maxCoeff();
        REQUIRE(max_error == Approx(0.).margin(1e-5));
    }
    REQUIRE(x_sol.maxCoeff() <= Approx(5.).margin(1e-3));
    REQUIRE(x_sol.minCoeff() >= Approx(-5.).margin(1e-3));
    REQUIRE(u_sol.maxCoeff() <= Approx(2.).margin(1e-3));
    REQUIRE(u_sol.minCoeff() >= Approx(-2.).margin(1e-3));
}

**Comment by EmbersArc** [comment]
That's very much to be expected. Is there a specific part of the setup that takes a disproportionate amount of time?

**Comment by szt008** [comment]
This is the result of running the following code.
Normally, the time of adding constraints and solving QP problem should be in an order of magnitude. However, the time to add constraints is more than ten times of solving the QP problem at present.

Time for adding constraints is 1.11352
Time for solving qp is 0.038684
Total time is 1.1522
===============================================================================
All tests passed (704 assertions in 1 test case)

using namespace cvx;

#include <ctime>
    

TEST_CASE("MPC QP")
{
    // This test solves an MPC problem with quadratic programming.
    clock_t start_sovle_qp,start_add_constraints,finish_add_constraints,finish_sovle_qp;
    
    size_t T = 700; // time horizon

    Eigen::MatrixXd A(2, 2);
    A << 2, -1, 1, 0.2;
    Eigen::MatrixXd B(2, 1);
    B << 1, 0;
    Eigen::VectorXd x0(2);
    x0 << 3, 1;

    OptimizationProblem qp;

    // Create variables
    MatrixX x = qp.addVariable("x", 2, T + 1);
    MatrixX u = qp.addVariable("u", 1, T);
    start_add_constraints = clock();
    // Dynamics
    for (size_t t = 0; t < T; t++)
    {
        qp.addConstraint(equalTo(x.col(t + 1), par(A) * x.col(t) + par(B) * u.col(t)));
    }

    // State and control limits
    qp.addConstraint(box(-5., x, 5.));

    // Equivalent to
    // qp.addConstraint(box(-2., u, 2.));
    qp.addConstraint(greaterThan(u, -2.));
    qp.addConstraint(lessThan(u, 2.));

    // Boundary constraints
    qp.addConstraint(equalTo(x.col(0), par(x0)));
    qp.addConstraint(equalTo(x.col(T), 0.));

    // Cost function
    qp.addCostTerm(x.squaredNorm() + u.squaredNorm());
    finish_add_constraints = clock();
    // Print the problem for inspection
    start_sovle_qp = clock();
    // Create and initialize the solver instance.
    osqp::OSQPSolver solver(qp);

    solver.setAlpha(1.);
    
    
    // Solve the problem and get the solution
    solver.solve(false);
    finish_sovle_qp = clock();
    std::cout<<"Time for adding constraints is "<<((double)(finish_add_constraints-start_add_constraints))/CLOCKS_PER_SEC<<std::endl;
    std::cout<<"Time for solving qp is "<<((double)(finish_sovle_qp-start_sovle_qp))/CLOCKS_PER_SEC<<std::endl;
    std::cout<<"Total time is "<<((double)(finish_sovle_qp-start_add_constraints))/CLOCKS_PER_SEC<<std::endl;
    Eigen::MatrixXd x_sol = eval(x);
    Eigen::MatrixXd u_sol = eval(u);

    // Check solution
    for (size_t t = 0; t < T; t++)
    {
        const Eigen::VectorXd x_solution = x_sol.col(t + 1);
        const Eigen::VectorXd x_propagate = A * x_sol.col(t) + B * u_sol.col(t);
        const double max_error = (x_propagate - x_solution).cwiseAbs().maxCoeff();
        REQUIRE(max_error == Approx(0.).margin(1e-5));
    }
    REQUIRE(x_sol.maxCoeff() <= Approx(5.).margin(1e-3));
    REQUIRE(x_sol.minCoeff() >= Approx(-5.).margin(1e-3));
    REQUIRE(u_sol.maxCoeff() <= Approx(2.).margin(1e-3));
    REQUIRE(u_sol.minCoeff() >= Approx(-2.).margin(1e-3));
}

**Comment by szt008** [comment]
According to further testing, I found that the following code is extremely time-consuming. It may be that squarednorm() called the sparse matrix API to process a non sparse matrix.

qp.addCostTerm(x.squaredNorm() + u.squaredNorm());

**Comment by EmbersArc** [comment]
Oh okay I see. You increased the time horizon by a factor of 100. Are you using the release configuration? It shaves off a whole second in my case. Why do you think there was a call to the sparse API?

Epigraph isn't optimized to be insanely fast with the problem formulation. Is the time it takes to construct a problem an issue in your case?

**Comment by szt008** [comment]
When horizon is short, setting cost term accounts for a large proportion of the total time to solve the problem. When horizon is long, this phenomenon has become even more obvious.
When I set cost matrix P Q directly using osqp lib, it takes much short time to calculate the cost matrix directly without epigraph API.
Could epigraph  lib provide an interface to directly assign values to the cost matrix P and Q? In that way it would better adapt to the application of online solution.

**Comment by EmbersArc** [comment]
Epigraph supports sparse Eigen matrices and using those to formulate the cost function might be a lot faster. However then I'm not sure what the benefit of using Epigraph is anymore when you're constructing the sparse matrices yourself.

Out of curiosity: What changes do you make to your problem that require you to reformulate it each time? Are you sure that [dynamic parameters](https://embersarc.github.io/Epigraph/expressions_8hpp.html#a1d984e3625f4b93568f4d23ae1545706) are not what you're looking for?

**Comment by gelinhe** [comment]
After my test, x.squaredNorm() + u.squaredNorm() is very time consuming, not qp.addCostTerm function itself. It found that the calculation time of squaredNorm() is considerable, you can try different time horizon.

**Comment by EmbersArc** [comment]
No doubt that squaredNorm is slow there. I'll try to figure out why. Did you try dynpar()?

**Comment by gelinhe** [comment]
dynpar has not been tested yet，I'll test it tomorrow

**Comment by EmbersArc** [comment]
Oops, sorry @gelinhe, I thought you were @szt008, ignore the part about dynpar.

**Comment by EmbersArc** [comment]
So the issue is that Eigen uses `operator+` for cvx::Scalar which is way slower than `operator+=`. I will try but I don't think there is a straightforward way to fix this. But the problem formulation part should only be run once and not be in any performance critical sections anyway. @szt008 Did `dynpar` work for your application?
